project:
  type: book
book:
  title: "Case study 1: mouse kidney peptide dataset"
  author: "Yinyue Zhu"
  chapters:
    - index.qmd
    - 2-mouse_kidney.ipynb
    - 3-mouse_kidney_segmentation.qmd
    - 4-timsconvert_comparison.qmd
# toc: true
# toc-location: left
# number-sections: true
execute:
  echo: true
format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: scrreprt